### PR TITLE
Restructure, add go modules, add a go package, remove `rebuild.sh`, add a Makefile

### PR DESCRIPTION
**Pull request by xyproto**
These changes:

* Splits out `proxima5` and `mkassets` in separate `cmd` directories + a package, which is conventional.
* Adds go module files and vendors dependencies.
* Adds a `Makefile`, for easy packaging for Linux distros with `DESTDIR=... make install`.
* Removes `rebuild.sh`.

The go module system (available in Go 1.11 and above) + vendored dependencies makes sure that as long as you have checked out the sources, you can build proxima5, even without an internet connection at build-time.

Accept or reject at will. Thanks for creating the `tcell` package!

### CODE REVIEW

**Comment by gdamore** [comment]
You've pulled in tcell into the vendor directory.  I'd rather not do that.  I'm the author of both packages after all.

**Comment by xyproto** [comment]
Pulling in all dependencies into the vendor directory is common practice when vendoring dependencies.

Even if you are the author of both proxima5 and tcell, you might want that people having a copy of the proxima5 source code would be able to build it in the future, regardless of the uptime and status of `https://github.com/gdamore/tcell`.

If you are against vendoring in general, I can update my pull request to not vendor dependencies.

**Comment by xyproto** [comment]
Squashed the commits.

**Comment by xyproto** [comment]
It's hard to test go.mod and go.sum, without making changes to the actual repository. Closing pull request.

**Pull request closed without merging**
